ARG VERSION=10.4
FROM mariadb/server:${VERSION}
EXPOSE 3306


# Run command 
# docker run -d --name todol 
# -p 6001:3306 \
# -v todo-db:/etc/todos \
# -e MYSQL_ROOT_PASSWORD=root \
# -e MYSQL_DATABASE=ToDoList \
# todolist-database-image